---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bfnpALSprocessor

<!-- badges: start -->
<!-- badges: end -->

This package is used to process and harmonize all available ALS data in the Bavarian Forest National Park and document the individual processing steps performed for each dataset. It mainly builds ready-to-use functions to reapeat certain processing steps to several different data sets and relies on lidR, sf and terra.

This package includes the functions used and a full documentation of all the processing steps applied to the available ALS data in the Bavarian forest national park.

Install this package using
`devtools::install_github("jebenbeck/bfnpALSprocessor", dependencies = T)`

This package was developed and tested using the following dependencies:

dplyr (>= 1.1.4),
future (>= 1.34.0),
ggplot2 (>= 3.5.1),
lidR (>= 4.1.2),
mapview (>= 2.11.2),
sf (>= 1.0.19),
stringr (>= 1.5.1),
terra (>= 1.8.10),
tools (>= 4.4.1),
yardstick (>= 1.3.2)

All functions can be seen here: https://jebenbeck.github.io/bfnpALSprocessor/reference/index.html 
