#' Assess the accuracy of a set of ground control points with boxplots
#'
#' @description This function takes the output of `merge_gcps()` and provides boxplots for the differences per gcp in X,Y,Z directions
#' per site
#' @param gcp_data object of class `spatial points` as generated by `merge_gcps())`.
#' @param export logical of length 1. Should the result be exported to a png ? Defaults to FALSE.
#' @param filename character, optional, name of the resulting png file
#' @param output_path character, optional, path to folder where the file will be exported to
#' @return aa_create_boxplots: ggplot2 object
#' @export
#'
#' @examples
#' \dontrun{
#' generate boxplots:
#' GCPs_2017_ref <- st_read("I:/misc/GCPs/2017-06/GCPs_ALS_2017_ref.gpkg")
#' aa_create_boxplots(gcp_data = GCPs_2017_ref, export = T, filename = "Difference_GCPs_ALS_2017",
#'                    output_path = "I:/misc/GCPs/2017-06")
#' calculate metrics:
#' metrics <- aa_metrics(GCPs_2017_ref, export = T, filename = "Metrics_ALS_2017", output_path = "I:/misc/GCPs/2017-06")
#' metrics
#' }


aa_create_boxplots <- function(gcp_data, export = F, filename, output_path){

  #' re-format data for better visualization:
  data <- gcp_data %>% pivot_longer(cols = c(deltaX, deltaY, deltaZ), names_to = "Direction", values_to = "Difference") %>%
    mutate(Direction = recode(Direction, "deltaX" = "X", "deltaY" = "Y", "deltaZ" = "Z"))

  #' generate the plot:
  bplot <- ggplot(data = data, aes(y = Difference, x = AOI)) +
    geom_hline(yintercept = 0, color = "darkgrey", linewidth = 0.5) +
    geom_point(position = position_jitter(width = 0.1), shape = 1, size = 0.1, color = "blue") +
    geom_boxplot(outliers = F, color = "black", fill = NA, width = 0.2) +
    facet_wrap(vars(Direction), nrow = 3, ncol = 1, shrink = F) +
    labs (y = "Difference (meter)") +
    theme_bw() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
    )

  plot(bplot)

  if (export == T) {
    #' export the plot to disk:
    ggsave(filename = paste0(filename, ".png"),
           plot = bplot, device = "png",
           path = output_path,
           width = 200, height = 200, units = "mm", dpi = 300)
  }

}
