#' Assess the accuracy of a set of ground control points by calculating metrics
#'
#' @description This function takes the output of `merge_gcps()` and provides accuracy metrics for the differences per gcp in X,Y,Z directions
#' per site
#' @param gcp_data object of class `spatial points` as generated by `merge_gcps())`.
#' @param export logical of length 1. Should the result be exported to a csv file? Defaults to FALSE.
#' @param filename character, optional, name of the resulting csv file
#' @param output_path character, optional, path to folder where the csv file will be exported to
#' @return data frame
#' @export
#'
#' @examples
#' \dontrun{
#' generate boxplots:
#' GCPs_2017_ref <- st_read("I:/misc/GCPs/2017-06/GCPs_ALS_2017_ref.gpkg")
#' aa_create_boxplots(gcp_data = GCPs_2017_ref, export = T, filename = "Difference_GCPs_ALS_2017",
#'                    output_path = "I:/misc/GCPs/2017-06")
#' calculate metrics:
#' metrics <- aa_metrics(GCPs_2017_ref, export = T, filename = "Metrics_ALS_2017", output_path = "I:/misc/GCPs/2017-06")
#' metrics
#' }


aa_metrics <- function(gcp_data, export = F, filename, output_path){

  #' Convert data to long format for easier processing
  df_long <- gcp_data %>%
    st_drop_geometry() %>%
    select(deltaX, deltaY, deltaZ, deltaH) %>%
    pivot_longer(cols = everything(), names_to = "direction", values_to = "error")

  #' Compute accuracy metrics using yardstick
  summary_table <- df_long %>%
    group_by(direction) %>%
    summarise(
      RMSE = round(rmse_vec(rep(0, n()), error), 3),
      MAE = round(mae_vec(rep(0, n()), error), 3),
      Bias = round(mean(error), 3),
      SD = round(sd(error), 3)
    ) %>%
    mutate(direction = recode(direction, "deltaX" = "X", "deltaY" = "Y", "deltaZ" = "Z", "deltaH" = "H"))

  #' Export table to csv
  if (export == T) {
    write.csv2(summary_table, file = paste0(output_path, "/", filename, ".csv"), row.names = F, dec = ".")
  }

  #' Print the final table
  return(summary_table)

}

