#' Merge ground control points of 2 datasets for further comparison
#'
#' @description This function takes two outputs of prepare_gcps() and merges them for comparison.
#' @param gcp_data_test object of class `spatial points` as generated by `bfnpALSprocessor::prepare_gcps())`.
#' This is the dataset the accurracy should be checked for
#' @param gcp_data_ref object of class `spatial points` as generated by `bfnpALSprocessor::prepare_gcps())`.
#' This is the reference dataset (i.e. the ALS 2019-2020 dataset)
#' @param export logical of length 1. Should the result be exported to a geopackage file? Defaults to FALSE.
#' @param filename character, optional, name of the resulting geopackage file
#' @param output_path character, optional, path to folder where the newly generated gpkg file will be exported to
#' @return sf points
#' @export
#'
#' @examples
#' \dontrun{
#' merge the GCPs with the reference GCPs:
#' GCPs_ref <- st_read("I:/misc/GCPs/2019-2020/GCPs_ALS_2019.gpkg")
#' GCPs_2017 <- st_read("I:/misc/GCPs/2017-06/GCPs_ALS_2017.gpkg")
#' GCPs_2017_ref <- merge_GCPs(GCPs_2017, GCPs_ref, export = T, filename = "GCPs_ALS_2017_ref", output_path = "I:/misc/GCPs/2017-06")
#' }



merge_GCPs <- function(gcp_data_test, gcp_data_ref, export = F, filename = NULL, output_path = NULL) {

  #' calculate indices describing the nearest feature:
  nearest_indices <- st_nearest_feature(gcp_data_ref, gcp_data_test)

  # Add corresponding matches from the test data to the reference data
  gcp_data_ref$matchedID <- gcp_data_test$ID[nearest_indices]

  # Join attributes
  gcp_data_test_ref <- left_join(as.data.frame(gcp_data_test), as.data.frame(gcp_data_ref),
                                 by = c("ID" = "matchedID"), suffix = c("", "_ref"), keep = F) %>%
    rename("X_obs" = "X", "Y_obs" = "Y", "Z_obs" = "Z") %>%
    mutate(deltaX = X_obs - X_ref,
           deltaY = Y_obs - Y_ref,
           deltaH = sqrt(deltaX^2 + deltaY^2),  # Horizontal Error
           deltaZ = Z_obs - Z_ref) %>%
    filter(abs(deltaX) < 5,
           abs(deltaY) < 5,
           abs(deltaZ) < 5) %>%        #' filter points that are less the 5 m apart to their match
    select(ID, Description, AOI, X_obs, Y_obs, Z_obs, X_ref, Y_ref, Z_ref, deltaX, deltaY, deltaH, deltaZ, geom) %>%
    st_as_sf()

  if (export == T) {
    #' export to disk:
    st_write(gcp_data_test_ref, paste0(output_path, "/", filename, ".gpkg"), append = F)
  }

  return(gcp_data_test_ref)

}
