#' Prepare ground control points derived in cloud compare for further analysis
#'
#' @description This function takes a list of txt-files generated by the CloudCompare point picking tool and converts them to a single
#' geopackage layer. The points represent GCPs sampled in the point clouds within the pre-defined AOIs.
#'
#' @param input_path character path to the folder where one or several txt files are stored in the format exported by
#' the cloud compare point picking tool.
#' @param output_path character path to folder where the newly generated gpkg file will be exported to
#' @param crs character path, epsg code of coordinate reference system. Defaults to "EPSG:25832"
#' @param filename character, name of the geopackage file
#' @param polygons object of class `spatial polygons` featuring an attribute with the names of the polygons; used to group
#' the output by polygon area.
#' @return sf points
#' @export
#'
#' @examples
#' \dontrun{
#' load AOIs:
#' AOIs <- st_read("I:/misc/test_areas.gpkg", layer = "AOIs_UTM")
#' prepare the GCPs as generated using CloudCompare:
#' GCPs_2017 <- prepare_GCPs(input_path = "I:/misc/GCPs/2017-06", output_path = "I:/misc/GCPs/2017-06",
#' filename = "GCPs_ALS_2017", polygons = AOIs)
#' }



prepare_GCPs <- function(input_path, output_path, crs = "EPSG:25832", filename, polygons){

  #' list all txt files generated by CloudCompare point picking tool:
  file_list <- list.files(input_path, pattern = "\\.txt$", full.names = T)

  #' process the data:

  data <- lapply(file_list, read.table, header = F, sep = ",") %>%  # Read all files into a list
    bind_rows() %>%     #' combine tha datasets
    rename_with(~ c("Description", "X", "Y", "Z")) %>%      #' rename columns
    st_as_sf(coords = c("X", "Y"), crs = crs, remove = F) %>%      #' convert to spatial data
    st_join(AOIs["name"]) %>%       #' overlay GCPs with polygons to get info on AOI
    rename(AOI = name) %>%
    group_by(AOI) %>%
    mutate(ID = paste0(substr(AOI, 1, 3), "_", row_number()),  .before = everything()) %>%  #' generate an unique ID for all GCPs
    ungroup()

  #' export to disk:
  st_write(data, paste0(output_path, "/", filename, ".gpkg"), append = F)

  return(data)

}
